use crate::io_bridge::command_vector::{CommandVector, MAX_JOINTS};

/// Safety interceptor for commands destined for the drives.
///
/// The community or an external hardware manufacturer may write an
/// OpenHalConfig (or a WASM Skill) with dirty data: a NaN, a sign
/// inversion, or an infinite value generated by a faulty sensor. If such a
/// command reached the real motors, the robot would jerk violently and
/// destroy itself.
///
/// This module scans the command vector **before** dispatch
/// and blocks every anomaly: NaN/Infinity are instantly replaced with
/// the last safe value recorded in the previous tick, then the command
/// is clamped to the physical limits declared in the JSON. Zero allocations:
/// the history lives in a pre-allocated static array.
///
/// Runs exclusively on the CPU **Core 1**, inside the dedicated thread
/// of the 100 Hz control loop (`RealTimeControlLoop` in
/// `diagnostics::frequency_enforcer`): the sanitization never shares the
/// cache with the Core 2 Wasmtime runtime.
pub struct VectorSanitizer {
    last_safe: [f32; MAX_JOINTS],
}

impl VectorSanitizer {
    pub const fn new() -> Self {
        Self {
            last_safe: [0.0; MAX_JOINTS],
        }
    }

    /// Cleans the vector of radical mathematical anomalies and clamps it before
    /// dispatch to the HAL. The command is modified *in-place*:
    ///
    /// 1. NaN/Infinity → restore of the joint's last safe value;
    /// 2. out-of-range values → clamp to the physical limits declared in the JSON.
    ///
    /// Values that pass both checks become the new safe reference
    /// point for the following ticks.
    pub fn sanitize_and_clamp(&mut self, command: &mut CommandVector, limits: &[(f32, f32)]) {
        let n = command.len.min(MAX_JOINTS);
        for i in 0..n {
            let mut v = command.target_actuators[i];

            // 1. Protection against NaN/Infinity caused by incorrect
            //    third-party calculations (dirty JSON config, faulty sensor).
            if v.is_nan() || v.is_infinite() {
                v = self.last_safe[i];
                eprintln!(
                    "[WARN - HAL] Illegal value (NaN/Inf) detected on joint [{}]. Forced safe restore.",
                    i
                );
            }

            // 2. Hard clamping to the physical limits declared in the JSON.
            if let Some((min, max)) = limits.get(i) {
                v = v.clamp(*min, *max);
            }

            command.target_actuators[i] = v;
            self.last_safe[i] = v;
        }
    }
}

impl Default for VectorSanitizer {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn nan_replaced_with_last_safe_value() {
        let mut sanitizer = VectorSanitizer::new();
        let limits = vec![(0.0, 1.0), (0.0, 1.0), (0.0, 1.0)];
        let mut cmd = CommandVector::from_slice(&[0.5, f32::NAN, 2.0]);
        sanitizer.sanitize_and_clamp(&mut cmd, &limits);
        assert_eq!(cmd.as_slice(), &[0.5, 0.0, 1.0][..]);
    }

    #[test]
    fn infinite_restores_previous_tick_value() {
        let mut sanitizer = VectorSanitizer::new();
        let limits = vec![(-1.0, 1.0)];

        let mut ok = CommandVector::from_slice(&[0.7]);
        sanitizer.sanitize_and_clamp(&mut ok, &limits);
        assert_eq!(ok.as_slice(), &[0.7][..]);

        let mut bad = CommandVector::from_slice(&[f32::INFINITY]);
        sanitizer.sanitize_and_clamp(&mut bad, &limits);
        assert_eq!(bad.as_slice(), &[0.7][..]);
    }

    #[test]
    fn newest_safe_value_is_the_reference() {
        let mut sanitizer = VectorSanitizer::new();
        let limits = vec![(-1.0, 1.0)];

        let mut a = CommandVector::from_slice(&[0.3]);
        sanitizer.sanitize_and_clamp(&mut a, &limits);

        let mut b = CommandVector::from_slice(&[-0.9]);
        sanitizer.sanitize_and_clamp(&mut b, &limits);

        let mut bad = CommandVector::from_slice(&[f32::NAN]);
        sanitizer.sanitize_and_clamp(&mut bad, &limits);
        assert_eq!(bad.as_slice(), &[-0.9][..]);
    }

    #[test]
    fn clamps_out_of_range_values() {
        let mut sanitizer = VectorSanitizer::new();
        let limits = vec![(-2.0, 2.0), (0.0, 1.0)];
        let mut cmd = CommandVector::from_slice(&[10.0, -5.0]);
        sanitizer.sanitize_and_clamp(&mut cmd, &limits);
        assert_eq!(cmd.as_slice(), &[2.0, 0.0][..]);
    }

    #[test]
    fn missing_limits_pass_through() {
        let mut sanitizer = VectorSanitizer::new();
        let mut cmd = CommandVector::from_slice(&[42.0, -42.0]);
        sanitizer.sanitize_and_clamp(&mut cmd, &[]);
        assert_eq!(cmd.as_slice(), &[42.0, -42.0][..]);
    }
}
